#!/bin/sh

mount -t devtmpfs none /dev
mkdir /dev/pts
mount -t devpts none /dev/pts
mount -t sysfs sysfs /sys
hostname karllee
#mkdir -p /boot
#mount /dev/nanda /boot
MODULES_DIR=/lib/modules/`uname -r`

## mdev
echo /sbin/mdev > /proc/sys/kernel/hotplug
mdev -s


